version: "3.7"

services:
  api:
    container_name: "api-notifications"
    image: golang:latest
    working_dir: /api
    env_file:
      - .env
    volumes:
      - ".:/api"
    entrypoint: ["./entrypoint.sh", "reflex", "-c", "reflex.conf"]
    depends_on:
      - broker

  broker:
    container_name: "broker-notifications"
    image: rabbitmq:3-management-alpine
    hostname: "broker-notifications"
