basePath: /api/v1
definitions:
  models.Notification:
    properties:
      email:
        example: john.doe@foo.com
        type: string
      expo_push_token:
        example: ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]
        type: string
      message:
        example: Hello my friend
        type: string
      title:
        example: My Notification
        type: string
      type:
        example:
        - '["email"'
        - ' "push"]'
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
  license: {}
  title: Notifications API
  version: 0.1.0
paths:
  /notification:
    post:
      consumes:
      - application/json
      description: Add a new notification into the broker queues
      parameters:
      - description: Notification object
        in: body
        name: Notification
        required: true
        schema:
          $ref: '#/definitions/models.Notification'
      produces:
      - application/json
      responses:
        "204": {}
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: Add notification
      tags:
      - Notifications
swagger: "2.0"
